# Generated by Django 6.0.1 on 2026-01-08 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_major', models.CharField(blank=True, max_length=100, null=True)),
                ('category_middle', models.CharField(blank=True, max_length=100, null=True)),
                ('support_content', models.TextField(blank=True, null=True)),
                ('min_support_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('max_support_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('age_min', models.IntegerField(blank=True, default=0, null=True)),
                ('age_max', models.IntegerField(blank=True, default=0, null=True)),
                ('hosting_org', models.CharField(blank=True, max_length=100, null=True)),
                ('registering_org', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_org', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_registering_org', models.CharField(blank=True, max_length=100, null=True)),
                ('application_period', models.CharField(blank=True, max_length=255, null=True)),
                ('application_method', models.TextField(blank=True, null=True)),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('selection_method', models.TextField(blank=True, null=True)),
                ('ref_url1', models.URLField(blank=True, max_length=500, null=True)),
                ('ref_url2', models.URLField(blank=True, max_length=500, null=True)),
                ('app_url', models.URLField(blank=True, max_length=500, null=True)),
                ('provider_group', models.CharField(blank=True, max_length=100, null=True)),
                ('provision_method', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_status', models.CharField(blank=True, max_length=50, null=True)),
                ('period_type', models.CharField(blank=True, max_length=50, null=True)),
                ('period_type_biz', models.CharField(blank=True, max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=50, null=True)),
                ('income_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('major_requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=255, null=True)),
                ('education_requirement', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('region_scope', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_condition', models.TextField(blank=True, null=True)),
                ('exclusion_criteria', models.TextField(blank=True, null=True)),
                ('operating_org', models.CharField(blank=True, max_length=100, null=True)),
                ('other_support_condition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
