# Generated by Django 5.2.10 on 2026-01-22 08:35
# 수정일: 2026-01-22
# 수정내용: Antigravity - 불필요한 모델(Order, Product, Review) 제거 후 최신 모델 구조만 포함하도록 초기 마이그레이션 파일 최종 갱신

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('top_code', models.CharField(blank=True, max_length=50, null=True)),
                ('code_id', models.CharField(blank=True, max_length=50, null=True)),
                ('code_name', models.CharField(max_length=200)),
                ('order_number', models.IntegerField(default=10)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gym_common',
                'ordering': ['order_number', 'code_name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_count', models.IntegerField(default=0)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gym_notice',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('practice_number', models.CharField(max_length=50, unique=True)),
                ('practice_name', models.CharField(max_length=50)),
                ('practice_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('practice_description', models.TextField()),
                ('practice_status', models.CharField(default='PENDING', max_length=20)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gym_practice',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gym_user',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_detail', serialize=False, to='core.userprofile')),
                ('is_developer', models.BooleanField(default=True)),
                ('job_role', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gym_userdetail',
            },
        ),
    ]
