# Generated by Django 5.2.10 on 2026-01-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('common_id', models.AutoField(primary_key=True, serialize=False)),
                ('top_code', models.CharField(blank=True, max_length=50, null=True)),
                ('code_id', models.CharField(blank=True, max_length=50, null=True)),
                ('code_name', models.CharField(max_length=200)),
                ('order_number', models.IntegerField(default=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gym_common',
                'ordering': ['order_number', 'code_name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_count', models.IntegerField(default=0)),
                ('recorded_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(max_length=200)),
                ('board_contents', models.TextField()),
                ('open_date', models.DateTimeField(blank=True, null=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gym_post',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_seq', models.IntegerField(blank=True, null=True, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('user_nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('password', models.CharField(max_length=128)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gym_user',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_detail', serialize=False, to='core.userprofile')),
                ('detail_seq', models.IntegerField(blank=True, null=True)),
                ('is_developer', models.BooleanField(default=True)),
                ('job_role', models.TextField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gym_userdetail',
            },
        ),
    ]
