# Generated by Django 5.2.10 on 2026-01-21 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Common',
            fields=[
                ('common_id', models.AutoField(primary_key=True, serialize=False)),
                ('top_code', models.CharField(blank=True, max_length=50, null=True)),
                ('code_id', models.CharField(blank=True, max_length=50, null=True)),
                ('code_name', models.CharField(max_length=200)),
                ('order_number', models.IntegerField(default=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('create_id', models.CharField(blank=True, max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, max_length=50, null=True)),
                ('use_yn', models.CharField(default='Y', max_length=1)),
            ],
            options={
                'db_table': 'gym_common',
                'ordering': ['order_number', 'code_name'],
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user_id', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_detail', serialize=False, to='core.userprofile')),
                ('detail_seq', models.IntegerField(blank=True, null=True)),
                ('is_developer', models.BooleanField(default=True)),
                ('job_role', models.CharField(blank=True, max_length=255, null=True)),
                ('interests', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'gym_userdetail',
            },
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='board_contents',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='board_title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_at',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='board_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='create_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='open_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='update_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='use_yn',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='create_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='update_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='use_yn',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_seq',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='post',
            table='gym_post',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='gym_user',
        ),
    ]
